#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-plotly
Version  : 5.8.0
Release  : 27
URL      : https://files.pythonhosted.org/packages/2f/fe/53c316e6ba1564576b825a5bc5c7a31be6b6d6d6d04910346a975c2852dc/plotly-5.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/2f/fe/53c316e6ba1564576b825a5bc5c7a31be6b6d6d6d04910346a975c2852dc/plotly-5.8.0.tar.gz
Summary  : An open-source, interactive data visualization library for Python
Group    : Development/Tools
License  : MIT
Requires: pypi-plotly-data = %{version}-%{release}
Requires: pypi-plotly-license = %{version}-%{release}
Requires: pypi-plotly-python = %{version}-%{release}
Requires: pypi-plotly-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jupyterlab)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(tenacity)
BuildRequires : pypi(wheel)

%description
# plotly.py
<table>
<tr>
<td>Latest Release</td>
<td>
<a href="https://pypi.org/project/plotly/"/>
<img src="https://badge.fury.io/py/plotly.svg"/>
</td>
</tr>
<tr>
<td>User forum</td>
<td>
<a href="https://community.plotly.com/"/>
<img src="https://img.shields.io/badge/help_forum-discourse-blue.svg"/>
</td>
</tr>
<tr>
<td>PyPI Downloads</td>
<td>
<a href="https://pepy.tech/project/plotly"/>
<img src="https://pepy.tech/badge/plotly/month"/>
</td>
</tr>
<tr>
<td>License</td>
<td>
<a href="https://opensource.org/licenses/MIT"/>
<img src="https://img.shields.io/badge/License-MIT-yellow.svg"/>
</td>
</tr>
</table>

%package data
Summary: data components for the pypi-plotly package.
Group: Data

%description data
data components for the pypi-plotly package.


%package license
Summary: license components for the pypi-plotly package.
Group: Default

%description license
license components for the pypi-plotly package.


%package python
Summary: python components for the pypi-plotly package.
Group: Default
Requires: pypi-plotly-python3 = %{version}-%{release}

%description python
python components for the pypi-plotly package.


%package python3
Summary: python3 components for the pypi-plotly package.
Group: Default
Requires: python3-core
Provides: pypi(plotly)
Requires: pypi(tenacity)

%description python3
python3 components for the pypi-plotly package.


%prep
%setup -q -n plotly-5.8.0
cd %{_builddir}/plotly-5.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1652281763
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-plotly
cp %{_builddir}/plotly-5.8.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-plotly/c340b1b30a740d882e192d6d38588465417cfdc4
cp %{_builddir}/plotly-5.8.0/jupyterlab_plotly/labextension/static/478.f9a7116e09cbfb956212.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-plotly/502fa657dd5f79d91bf30b9683e9df3562405e51
cp %{_builddir}/plotly-5.8.0/jupyterlab_plotly/nbextension/index.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-plotly/f3e379e00b9963b93f1e16ac14cb1866635caed5
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/nbconfig/notebook.d/jupyterlab-plotly.json

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/labextensions/jupyterlab-plotly/package.json
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/133.05656a8806721e5cdc34.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/423.13b35dff1663e01b2912.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/478.f9a7116e09cbfb956212.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/478.f9a7116e09cbfb956212.js.LICENSE.txt
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/486.52aa9063b291ec574154.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/486.52aa9063b291ec574154.js.LICENSE.txt
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/657.91c14f525949f657ae86.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/879.799d701fea3e64d178cf.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/remoteEntry.e36921af02dc11718a41.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/style.js
/usr/share/jupyter/nbextensions/jupyterlab-plotly/extension.js
/usr/share/jupyter/nbextensions/jupyterlab-plotly/index.js
/usr/share/jupyter/nbextensions/jupyterlab-plotly/index.js.LICENSE.txt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-plotly/502fa657dd5f79d91bf30b9683e9df3562405e51
/usr/share/package-licenses/pypi-plotly/c340b1b30a740d882e192d6d38588465417cfdc4
/usr/share/package-licenses/pypi-plotly/f3e379e00b9963b93f1e16ac14cb1866635caed5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
