#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-plotly
Version  : 5.17.0
Release  : 48
URL      : https://files.pythonhosted.org/packages/c7/bd/6516a9f3105cf15bf5892b2eec6eac4dd1645a4b1ed82ae86e0a044dab36/plotly-5.17.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c7/bd/6516a9f3105cf15bf5892b2eec6eac4dd1645a4b1ed82ae86e0a044dab36/plotly-5.17.0.tar.gz
Summary  : An open-source, interactive data visualization library for Python
Group    : Development/Tools
License  : MIT
Requires: pypi-plotly-data = %{version}-%{release}
Requires: pypi-plotly-license = %{version}-%{release}
Requires: pypi-plotly-python = %{version}-%{release}
Requires: pypi-plotly-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(jupyterlab)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# plotly.py
<table>
<tr>
<td>Latest Release</td>
<td>
<a href="https://pypi.org/project/plotly/"/>
<img src="https://badge.fury.io/py/plotly.svg"/>
</td>
</tr>
<tr>
<td>User forum</td>
<td>
<a href="https://community.plotly.com/"/>
<img src="https://img.shields.io/badge/help_forum-discourse-blue.svg"/>
</td>
</tr>
<tr>
<td>PyPI Downloads</td>
<td>
<a href="https://pepy.tech/project/plotly"/>
<img src="https://pepy.tech/badge/plotly/month"/>
</td>
</tr>
<tr>
<td>License</td>
<td>
<a href="https://opensource.org/licenses/MIT"/>
<img src="https://img.shields.io/badge/License-MIT-yellow.svg"/>
</td>
</tr>
</table>

%package data
Summary: data components for the pypi-plotly package.
Group: Data

%description data
data components for the pypi-plotly package.


%package license
Summary: license components for the pypi-plotly package.
Group: Default

%description license
license components for the pypi-plotly package.


%package python
Summary: python components for the pypi-plotly package.
Group: Default
Requires: pypi-plotly-python3 = %{version}-%{release}

%description python
python components for the pypi-plotly package.


%package python3
Summary: python3 components for the pypi-plotly package.
Group: Default
Requires: python3-core
Provides: pypi(plotly)
Requires: pypi(packaging)
Requires: pypi(tenacity)

%description python3
python3 components for the pypi-plotly package.


%prep
%setup -q -n plotly-5.17.0
cd %{_builddir}/plotly-5.17.0
pushd ..
cp -a plotly-5.17.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694800532
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-plotly
cp %{_builddir}/plotly-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-plotly/c340b1b30a740d882e192d6d38588465417cfdc4 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/nbconfig/notebook.d/jupyterlab-plotly.json
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/labextensions/jupyterlab-plotly/package.json
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/133.e85857c23bc96dec5e13.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/423.d0d3e2912c33c7566484.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/478.3105ed2766dbb1bb6616.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/478.3105ed2766dbb1bb6616.js.LICENSE.txt
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/486.6450efe6168c2f8caddb.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/486.6450efe6168c2f8caddb.js.LICENSE.txt
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/657.9df59cd7b5b5e72027cf.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/855.323c80e7298812d692e7.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/remoteEntry.56bf4b5dc66a26bcd462.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/style.js
/usr/share/jupyter/labextensions/jupyterlab-plotly/static/third-party-licenses.json
/usr/share/jupyter/nbextensions/jupyterlab-plotly/extension.js
/usr/share/jupyter/nbextensions/jupyterlab-plotly/index.js
/usr/share/jupyter/nbextensions/jupyterlab-plotly/index.js.LICENSE.txt

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-plotly/c340b1b30a740d882e192d6d38588465417cfdc4

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
